---
- name: This is how we deploy our databases
  hosts: databases
  tasks:
    - name: redis-server service
      become: true
      ansible.builtin.systemd:
        daemon_reload: yes
        name: redis-server
        state: started
        enabled: true

    - name: postgresql service
      become: true
      ansible.builtin.systemd:
        daemon_reload: yes
        name: postgresql
        state: started
        enabled: true
